# -----------------------------------------------------------------------------
# OpenManus-Lite 全局配置
# -----------------------------------------------------------------------------

# LLM 提供商配置 (例如 PPIO, OpenAI, Groq, etc.)
# api_type 是一个自定义字段，可以帮助你在代码中识别服务类型，但对于OpenAI兼容的API，它不是必需的。

[llm]
api_type = "ppio"
model = "deepseek/deepseek-v3-0324"                # 要使用的LLM模型
base_url = "https://api.ppinfra.com/v3/openai"  # API端点URL
# api_key = "......"                 # API密钥
max_tokens = 8192                                       # 响应中的最大令牌数
temperature = 0.0                                       # 控制随机性，值越低结果越确定
