# 工作区目录，用于存放 Agent 生成的文件
workspace_dir = "workspace"

# 日志配置
[log]
level = "INFO" # 日志级别，可以是 DEBUG, INFO, WARNING, ERROR, CRITICAL

# LLM 配置
[llm] #PPIO:
api_type = 'ppio'
model = "deepseek/deepseek-v3-0324"                                # The LLM model to use
base_url = "https://api.ppinfra.com/v3/openai"                     # API endpoint URL
# api_key = "...."                                      # Your API key
max_tokens = 8192                                                 # Maximum number of tokens in the response
temperature = 0.0

# Sandbox (Docker) 配置
[sandbox]
# Docker 镜像
image = "ubuntu:22.04"
# Agent 的工作目录
working_directory = "/workspace"
# 命令执行超时时间（秒）
timeout = 60
# 内存限制（例如: "512m", "1g"）
memory_limit = "512m"
# CPU 核心数限制（例如: 1.0, 1.5）
cpu_limit = 1.0
# 是否启用网络
network_enabled = False

# --------------------------------------------------------------------------------------------------
# Agent 配置
# --------------------------------------------------------------------------------------------------
[agent]
agent_name = "ManusAgent"
max_iterations = 10