# 工作区目录，用于存放 Agent 生成的文件
workspace_dir = "workspace"

# 日志配置
[log]
level = "INFO" # 日志级别，可以是 DEBUG, INFO, WARNING, ERROR, CRITICAL

# LLM 配置
[llm] #PPIO:
api_type = 'ppio'
model = "deepseek/deepseek-v3-0324"                                # The LLM model to use
base_url = "https://api.ppinfra.com/v3/openai"                     # API endpoint URL
api_key = "sk_4bIQwnJzG2B_Vzk291NsEBMNJba_AlyOtueQCKt23Zs"                                      # Your API key
max_tokens = 8192                                                 # Maximum number of tokens in the response
temperature = 0.0

# Sandbox (Docker) 配置
[sandbox]
# 使用的 Docker 镜像
image_name = "ubuntu:22.04"
# 沙箱的工作目录
workspace_mount_path = "/workspace"
# 命令执行的默认超时时间（秒）
timeout = 120
# 是否开启网络
network_enabled = false
# 内存限制 (e.g., "512m", "1g")
memory_limit = "512m"
# CPU 核心数限制 (e.g., 1.0, 1.5)
cpu_limit = 1.0