# -*- coding: utf-8 -*-
from core.llm import call_llm
from agents.prompts import PLANNING_INSTRUCTIONS

class PlanningAgent:
    """
    The Planning Agent.
    Responsible for receiving a user task and creating a series of executable steps.
    """
    def create_plan(self, task: str) -> str:
        """
        Generates a plan based on the user's task.

        Args:
            task (str): The initial user-defined task.

        Returns:
            str: A string containing the plan generated by the LLM, with each step on a new line.
        """
        print("🤔 PlanningAgent is thinking about how to plan the task...")

        # Construct the prompt for planning
        prompt = f"This is the task I need to accomplish: '{task}'\n\nPlease create a detailed, step-by-step plan for me."

        # Call the LLM to generate the plan
        plan_str = call_llm(prompt, instructions=PLANNING_INSTRUCTIONS)

        return plan_str
